name: Deploy
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    needs: check
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - run: cat src/System.js src/Client.js src/Peer.js src/Peers.js src/WebRTCManager.js src/WebSocketManager.js src/hash.js src/parse.js src/DataChecker.js > ./dist/Client.js
      - run: npm ci
      - run: npm run lint
      - uses: actions/configure-pages@v3
      - uses: actions/upload-pages-artifact@v2
        with:
          path: "./dist"
        id: deployment
      - uses: actions/deploy-pages@v2